### ISSUE TITLE
How to handle out-of-order/delayed data

### ISSUE THREAD

**Issue by AndyRao** [Stratio/Sparta#1571]
Spark streaming is the main computation engine of Sparta, but spark streaming use mini-batch to process data. If I want to do some aggregation on the event time filed of data. How sparta handle delayed arrive or out-of-order data? I think in most cases, users care more about event time of data, not arrival time.

**Comment by danielcsant** [comment]
Hi Andy,

You are right, most of the use cases we got are based on the event time of data. In these cases Sparta takes into account this event time as part of the key for which Sparta aggregates. In case we have for example a cube aggregating by hour, Sparta will aggregate this hour with the mini-batches helped by the checkpointing feature that Spark provides. Since this checkpointing use resources we have to tell Sparta a way to release them. This resources are released by telling Sparta the max event time to compute (the computeLast property of the cube). 

Hope the answer has been helpful

**Comment by AndyRao** [comment]
It's very helpful, I will check the code, thanks
