### ISSUE TITLE
Elasticsearch set string fields to analyzed as default

### ISSUE THREAD

**Issue by danielcsant** [Stratio/Sparta#287]
Solved running curl -XPUT localhost:9200/test -d '{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "default" : {
                    "type" : "keyword"
                }
            }
        }
    }
}'

for each index before is created

**Comment by gserranojc** [comment]
Use the correct driver for scala and elasticsearch. 

Opening a connection and sending all mappings and create the indexes if not exists.

**Comment by gserranojc** [comment]
This issue is repeated: 174

Elasticsearch create the mapping based on the schema and not let the connector believe dynamically. So we can assign a tokenizer or typeIndex the index.

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

We'll use this driver for Scala:

https://github.com/sksamuel/elastic4s

ElasticSearch for Spark not support bigDecimal type, we'll convert to double.
